apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port:  {{ .Values.service.wordpress.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "mysql.name" . }}
    tier: mysql
  clusterIP: {{ .Values.service.wordpress.clusterIP }}


